### ISSUE TITLE
Jupyter Notebook Nº3 - LC

### ISSUE THREAD

**Issue by inesgirao** [bopen/c3s-eqc-toolbox-template#175]
### Notebook description

I submit the notebook for use case 3 of LC dataset to deliver in the end of the month for tecnhical revision.

### Notebook link or upload

[C3S2_D520.5.3.14b_Quality_Assessment_User_Questions_LULC_UQ3_V0.0.zip](https://github.com/user-attachments/files/18218244/C3S2_D520.5.3.14b_Quality_Assessment_User_Questions_LULC_UQ3_V0.0.zip)

### Environment

<details>
Brotli==1.1.0
Cartopy==0.24.1
Mako==1.3.8
Markdown==3.7
MarkupSafe==3.0.2
PySocks==1.7.1
PyYAML==6.0.2
SQLAlchemy==2.0.36
SQLAlchemy-Utils==0.41.2
Send2Trash==1.8.3
affine==2.4.0
alembic==1.14.0
annotated-types==0.7.0
anyio==4.7.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array-api-compat==1.9.1
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.4
attrs==24.2.0
autocommand==2.2.2
babel==2.16.0
backports.tarfile==1.2.0
beautifulsoup4==4.12.3
bleach==6.2.0
c3s-eqc-automatic-quality-control==0.1.2.dev113+g12de045
cached-property==1.5.2
cacholote==1.4.0
cdsapi==0.7.5
certifi==2024.12.14
cf-units==3.3.0
cf-xarray==0.10.0
cffi==1.17.1
cfgrib==0.9.14.1
cftime==1.6.4.post1
cgul==0.0.4
charset-normalizer==3.4.0
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==3.1.0
comm==0.2.2
contourpy==1.3.1
cycler==0.12.1
dask==2024.12.0
datapi==0.1.1
debugpy==1.8.9
decorator==5.1.1
defusedxml==0.7.1
earthkit-data==0.11.4
earthkit-geo==0.3.0
earthkit-meteo==0.3.0
eccodes==2.39.0
ecmwflibs==0.6.3
entrypoints==0.4
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.21.1
filelock==3.16.1
findlibs==0.0.5
fonttools==4.55.2
fqdn==1.5.1
fsspec==2024.10.0
geopandas==1.0.1
greenlet==3.1.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.7
httpx==0.28.1
hyperframe==6.0.1
idna==3.10
importlib-metadata==8.5.0
importlib-resources==6.4.5
inflect==7.3.1
ipykernel==6.29.5
ipython==8.30.0
isoduration==20.11.0
jaraco.collections==5.1.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
jaraco.text==3.12.1
jedi==0.19.2
jinja2==3.1.4
joblib==1.4.2
json5==0.10.0
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter-client==7.4.9
jupyter-core==5.7.2
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter-server==2.14.2
jupyter-server-terminals==0.5.3
jupyterlab==4.3.3
jupyterlab-pygments==0.3.0
jupyterlab-server==2.27.3
kiwisolver==1.4.7
locket==1.0.0
lru-dict==1.3.0
matplotlib==3.9.3
matplotlib-inline==0.1.7
mistune==3.0.2
more-itertools==10.3.0
multiurl==0.3.3
nbclient==0.10.1
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
netCDF4==1.7.2
notebook==7.3.1
notebook-shim==0.2.4
numpy==2.2.0
overrides==7.7.0
packaging==24.2
pandas==2.2.3
pandocfilters==1.5.0
parso==0.8.4
partd==1.4.2
patsy==1.0.1
pdbufr==0.11.0
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.0.0
pip==24.3.1
pkgutil-resolve-name==1.3.10
platformdirs==4.3.6
plotly==5.24.1
pooch==1.8.2
prometheus-client==0.21.1
prompt-toolkit==3.0.48
properscoring==0.1
psutil==6.1.0
ptyprocess==0.7.0
pure-eval==0.2.3
pycparser==2.22
pydantic==2.10.3
pydantic-core==2.27.1
pydantic-settings==2.6.1
pygments==2.18.0
pyogrio==0.10.0
pyparsing==3.2.0
pyproj==3.7.0
pyshp==2.3.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
pytz==2024.2
pyzmq==24.0.1
rasterio==1.4.3
referencing==0.35.1
regionmask==0.13.0
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rioxarray==0.18.1
rpds-py==0.22.3
scipy==1.14.1
seaborn==0.13.2
setuptools==75.3.0
shapely==2.0.6
six==1.17.0
sniffio==1.3.1
soupsieve==2.5
stack-data==0.6.3
statsmodels==0.14.4
structlog==24.4.0
tabulate==0.9.0
tenacity==9.0.0
terminado==0.18.1
tinycss2==1.4.0
tomli==2.2.1
toolz==1.0.0
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
typeguard==4.3.0
types-python-dateutil==2.9.0.20241206
typing-extensions==4.12.2
typing-utils==0.1.0
tzdata==2024.2
uri-template==1.3.0
urllib3==2.2.3
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
wheel==0.44.0
xarray==2024.11.0
xhistogram==0.3.2
xskillscore==0.0.26
zipp==3.21.0
zstandard==0.23.0
/tmp/ipykernel_523282/4036504839.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

</details>

**Comment by malmans2** [comment]
Hi @inesgirao,

Same as #174: The notebook looks in good shape and runs smoothly on the VM.

You can request a permalink if you need to submit this notebook in the CIM.
I’ll be on leave next week, so if you need this completed before the end of the month, please make sure to handle it this week.

**Comment by inesgirao** [comment]
Thank you @malmans2 . Will do.

**Comment by inesgirao** [comment]
Hello @malmans2,

As requested by the data steamer, I’ve been working on reformulating the Jupyter notebook, but I keep encountering the same error when downloading. I’ve tried downloading the dataset using different networks, but the issue persists.

`---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py", line 500, in _delayed_download
    retrieve(collection_id, request)
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py", line 339, in retrieve
    return [file.path for file in _cached_retrieve(collection_id, request)]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/cacholote/cache.py", line 102, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py", line 324, in _cached_retrieve
    ds = earthkit.data.from_source("cds", collection_id, request, prompt=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/__init__.py", line 150, in from_source
    src = get_source(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/__init__.py", line 131, in __call__
    source = klass(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/core/__init__.py", line 22, in __call__
    obj.__init__(*args, **kwargs)
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/cds.py", line 126, in __init__
    self.path = [self._retrieve(dataset, r) for r in self.requests]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/cds.py", line 126, in <listcomp>
    self.path = [self._retrieve(dataset, r) for r in self.requests]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/cds.py", line 140, in _retrieve
    return_object = self.cache_file(
                    ^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/__init__.py", line 68, in cache_file
    return cache_file(owner, create, args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/core/caching.py", line 1056, in cache_file
    owner_data = create(path + ".tmp", args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/earthkit/data/sources/cds.py", line 136, in retrieve
    cds_result = self.client().retrieve(args[0], args[1])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/legacy_api_client.py", line 169, in retrieve
    submitted = self.client.submit_and_wait_on_results(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/api_client.py", line 458, in submit_and_wait_on_results
    return self._retrieve_api.submit(collection_id, **request).make_results()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/processing.py", line 489, in make_results
    self._wait_on_results()
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/processing.py", line 467, in _wait_on_results
    while not self.results_ready:
              ^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/processing.py", line 481, in results_ready
    results = self.make_results(wait=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/processing.py", line 495, in make_results
    results = Results.from_request("get", results_url, **self._request_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/processing.py", line 177, in from_request
    cads_raise_for_status(response)
  File "/home/inesvzgirao/miniconda3/envs/C3S/lib/python3.11/site-packages/datapi/processing.py", line 100, in cads_raise_for_status
    raise requests.HTTPError(message, response=response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/74fff391-d8e7-4a7b-ab80-7009aeb2e459/results
The job has failed.
Your request has not found some of the data expected to be present.
This may be due to temporary connectivity issues with the source data.
If this problem persists, please contact user support.
The job failed with: UrlNoDataError
"""

The above exception was the direct cause of the following exception:

HTTPError                                 Traceback (most recent call last)
Cell In[13], line 2
      1 # Download the dataset
----> 2 ds = download.download_and_transform(
      3     collection_id,
      4     requests,
      5     n_jobs=2
      6 )
      7 ds = ds.assign_coords(year=ds["time"].dt.year).swap_dims(time="year").drop("time")

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/c3s_eqc_automatic_quality_control/download.py:597, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, transform_func_kwargs, transform_chunks, n_jobs, invalidate_cache, cached_open_mfdataset_kwargs, quiet, **open_mfdataset_kwargs)
    595     assert not NOCACHE, "n_jobs must be 1 when NOCACHE is True"
    596     # Download all data in parallel
--> 597     joblib.Parallel(n_jobs=n_jobs)(
    598         _delayed_download(collection_id, request, cacholote.config.get())
    599         for request in request_list
    600     )
    602 if use_cache and transform_chunks:
    603     # Cache each chunk transformed
    604     sources = []

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py:2007, in Parallel.__call__(self, iterable)
   2001 # The first item from the output is blank, but it makes the interpreter
   2002 # progress until it enters the Try/Except block of the generator and
   2003 # reaches the first `yield` statement. This starts the asynchronous
   2004 # dispatch of the tasks to the workers.
   2005 next(output)
-> 2007 return output if self.return_generator else list(output)

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py:1650, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1647     yield
   1649     with self._backend.retrieval_context():
-> 1650         yield from self._retrieve()
   1652 except GeneratorExit:
   1653     # The generator has been garbage collected before being fully
   1654     # consumed. This aborts the remaining tasks if possible and warn
   1655     # the user if necessary.
   1656     self._exception = True

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py:1754, in Parallel._retrieve(self)
   1747 while self._wait_retrieval():
   1748 
   1749     # If the callback thread of a worker has signaled that its task
   1750     # triggered an exception, or if the retrieval loop has raised an
   1751     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1752     # worker traceback.
   1753     if self._aborting:
-> 1754         self._raise_error_fast()
   1755         break
   1757     # If the next job is not ready for retrieval yet, we just wait for
   1758     # async callbacks to progress.

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py:1789, in Parallel._raise_error_fast(self)
   1785 # If this error job exists, immediately raise the error by
   1786 # calling get_result. This job might not exists if abort has been
   1787 # called directly or if the generator is gc'ed.
   1788 if error_job is not None:
-> 1789     error_job.get_result(self.timeout)

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py:745, in BatchCompletionCallBack.get_result(self, timeout)
    739 backend = self.parallel._backend
    741 if backend.supports_retrieve_callback:
    742     # We assume that the result has already been retrieved by the
    743     # callback thread, and is stored internally. It's just waiting to
    744     # be returned.
--> 745     return self._return_or_raise()
    747 # For other backends, the main thread needs to run the retrieval step.
    748 try:

File ~/miniconda3/envs/C3S/lib/python3.11/site-packages/joblib/parallel.py:763, in BatchCompletionCallBack._return_or_raise(self)
    761 try:
    762     if self.status == TASK_ERROR:
--> 763         raise self._result
    764     return self._result
    765 finally:

HTTPError: 400 Client Error: Bad Request for url: https://cds.climate.copernicus.eu/api/retrieve/v1/jobs/74fff391-d8e7-4a7b-ab80-7009aeb2e459/results
The job has failed.
Your request has not found some of the data expected to be present.
This may be due to temporary connectivity issues with the source data.
If this problem persists, please contact user support.
The job failed with: UrlNoDataError`

Could there be a problem on the site’s end that might be causing this error? Do you have any ideas about what might be behind this issue?

Thank you for your attention.

Best regards,
Inês Girão

**Comment by malmans2** [comment]
Let's see, maybe it's just temporary connectivity issues as suggested by the error message.
I'm trying to download the requests right now. I'll let you know when I'm done.
