### ISSUE TITLE
Tagname not parseable by setuptools-scm

### ISSUE THREAD

**Issue by johtoblan** [bopen/c3s-eqc-toolbox-template#3]
See: https://github.com/bopen/c3s-eqc-toolbox-template/actions/runs/3329422866/jobs/5506618897#step:4:70
```
[...]
File "/tmp/pip-build-env-c0b905k8/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 203, in _parse_tag
          assert version is not None
```

Reproduced locally:
```
pip install -e .
Obtaining file:///home/johannestl/Desktop/c3s/c3s-eqc-toolbox-template
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/version.py:84: UserWarning: tag 'D520.2.3.1-2022Q3' no version found
        warnings.warn(f"tag {tag!r} no version found")
      Traceback (most recent call last):
        File "/home/johannestl/anaconda3/envs/c3s/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/johannestl/anaconda3/envs/c3s/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/johannestl/anaconda3/envs/c3s/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 446, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 59, in _assign_version
          maybe_version = _get_version(config)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 154, in _get_version
          parsed_version = _do_parse(config)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 101, in _do_parse
          version = _version_from_entrypoints(config) or _version_from_entrypoints(
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/_entrypoints.py", line 66, in _version_from_entrypoints
          version: ScmVersion | None = _call_entrypoint_fn(root, config, ep.load())
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/_entrypoints.py", line 40, in _call_entrypoint_fn
          return fn(root, config=config)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/git.py", line 181, in parse
          return _git_parse_inner(
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/git.py", line 224, in _git_parse_inner
          return meta(
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 226, in meta
          parsed_version = _parse_tag(tag, preformatted, config)
        File "/tmp/pip-build-env-7w1b_h9x/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 203, in _parse_tag
          assert version is not None
      AssertionError
      [end of output]
```
Seemingly fixed locally by using a more parseable tag (0.1)
```
(c3s) johannestl@pc5329:~/Desktop/c3s/c3s-eqc-toolbox-template$ git tag -a 0.1 -m "New tag"
(c3s) johannestl@pc5329:~/Desktop/c3s/c3s-eqc-toolbox-template$ pip install -e .
Obtaining file:///home/johannestl/Desktop/c3s/c3s-eqc-toolbox-template
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting cacholote
[...]
```

Related issue from setuptools_scm: https://github.com/pypa/setuptools_scm/issues/449

**Comment by malmans2** [comment]
Thanks! We issued a new release.
