### ISSUE TITLE
Installation of the package: "make qa" exits with errors

### ISSUE THREAD

**Issue by vincenzodetoma** [bopen/c3s-eqc-toolbox-template#4]
Hi I've still have some problems when installing the package. 
In particular, when running make qa as in the Readme, the process fails in the large file part, giving the following chain of errors:

check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/eqcuser/.cache/pre-commit/repo6vbaclmy/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range

Is this test crucial to correctly build the template? 
Everything else seems to work properly, since I'm able to run the template you provided in the notebooks folder. 

Thanks and have a nice day,
Vincenzo de Toma

**Comment by malmans2** [comment]
I don't think you need it at the moment. QA stands for quality assurance, and it's meant for developers (it runs a few pre-commit hook to make sure that the code is in good shape before pushing to GitHub).

Anyways, the QA passes on GitHub actions and is working fine on my local machine. It looks like something went wrong with the pre-commit cache. Try this from terminal:
- activate the environment
- `pre-commit clean`
- `make qa` again

**Comment by malmans2** [comment]
I had a quick look at the VM: The problem is that there is a very old version of git installed (`1.8.3.1` - released in 2013).
(I'm closing this issue as it's not related to this package)
