### ISSUE TITLE
Can't read index file

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#56]
### What happened?

Hi @malmans2 

I'm getting this error message with a dataset that I have downloaded a couple of days back. Is it an issue with the cache?

S.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

from c3s_eqc_automatic_quality_control import diagnostics, download

start = "1980"
stop = None  # None: present

collection_id = "reanalysis-era5-pressure-levels"
request = {
'product_type': 'reanalysis',
        'format': 'grib',
        'variable': 'geopotential',
        'pressure_level': '500',
        'area': [
            90, -180, 30,
            180,
        ],
        "time": "00:00",
}
requests = download.update_request_date(request, start=start, stop=stop)

ds = download.download_and_transform(
    collection_id,
    requests,
#    transform_func=diagnostics.spatial_weighted_mean,
    chunks={"year": 1},
)
```

### Relevant log output

```Python
100%|██████████| 44/44 [00:01<00:00, 35.29it/s]
Can't read index file '/data/wp5/.cacholote/cache_files/b8b7da201fa7215808e719219983ccdf.grib.923a8.idx'
Traceback (most recent call last):
  File "/data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cfgrib/messages.py", line 547, in from_indexpath_or_filestream
    self = cls.from_indexpath(indexpath)
  File "/data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cfgrib/messages.py", line 429, in from_indexpath
    index = pickle.load(file)
EOFError: Ran out of input
Can't read index file '/data/wp5/.cacholote/cache_files/87b5350763e67cef70b93bdeead4d631.grib.923a8.idx'
Traceback (most recent call last):
  File "/data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cfgrib/messages.py", line 547, in from_indexpath_or_filestream
    self = cls.from_indexpath(indexpath)
  File "/data/common/mambaforge/envs/wp5/lib/python3.10/site-packages/cfgrib/messages.py", line 429, in from_indexpath
    index = pickle.load(file)
EOFError: Ran out of input
```

### Environment

<details>

</details>

**Comment by sandrocalmanti** [comment]
Ok, fixed
